config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/list'

  root "pages#home"
  get "about" => "pages#about"
  get "list" => "pages#list"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Places", list_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- .container-fluid -->
</nav>

</div><!-- /.container --> 
</nav>

app/views/layouts/_pagenumber.html.erb
<div class="container">

<ul class="pagination">
  <li><a href="#">&laquo;</a></li>
  <li><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">4</a></li>
  <li><a href="#">5</a></li>
  <li><a href="#">&raquo;</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
</head>
<body>

		
		<%= render 'layouts/header' %>


		<div class="container">



<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>



     
  			<%= yield %>


		

		</div>

<%= render 'layouts/pagenumber' %>
</body>
</html>

app/views/pages/about.html.erb
<h1> About Us </h1>
<p> We understand your frustrations with finding the right place. So we're here to make it better</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Finding more options to students </h1>
  <p>"Good food is nessesary to make your university experience complete" - Harvey Dent, McGill class of 2018</p>
  <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
</div>


<div 
    



<ul class="pagination pagination-lg">  
<button type="button" class="btn btn-default btn-lg">On Campus</button>



<button type="button" class="btn btn-default btn-lg">Off Campus</button>


  </div>








</ul>






<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x300" alt="...">
      <div class="caption">
        <h3>New York University </h3>
        <p>The apple of the city. House for sale !</p>
        <p><a href="#" class="btn btn-primary" role="button">See More</a> 
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x300" alt="...">
      <div class="caption">
        <h3>Boston </h3>
        <p>Rooms for rent !</p>
        <p><a href="#" class="btn btn-primary" role="button">See More</a> 
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x300" alt="...">
      <div class="caption">
        <h3>Miami </h3>
        <p>Rooms by the beach for rent ! </p>
        <p><a href="#" class="btn btn-primary" role="button">See More</a> 
    </div>
  </div>
</div>

app/views/pages/list.html.erb
<h1> Search for places </h1>


<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filters <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Views</a></li>
            <li><a href="#">Rating</a></li>
            <li><a href="#">Upload date</a></li>
            
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      



          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->






  
</nav